name: ts-rest-api

services:
  postgres-dev:
    image: postgres
    ports:
      - 5555:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: _ts_rest_api
    volumes:
      - dev-data:/var/lib/postgresql/data
    profiles:
      - dev

volumes:
  dev-data:
