name: ts-rest-api

services:
  postgres-dev:
    image: postgres
    ports:
      - 5555:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: _ts_rest_api
    volumes:
      - dev-data:/var/lib/postgresql/data
    profiles:
      - dev

  postgres-prod:
    image: postgres
    expose:
      - 5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: _ts_rest_api
    volumes:
      - prod-data:/var/lib/postgresql/data
    profiles:
      - prod

  api:
    image: mkvlrn/eteg-challenge
    depends_on:
      - postgres-prod
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    environment:
      DATABASE_URL: 'postgres://root:root@postgres-prod:5432/_ts_rest_api'
      PORT: 4000
      NODE_ENV: production
    profiles:
      - prod

volumes:
  dev-data:
  prod-data:
