name: test-and-analyze
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: install dependencies
        run: yarn install
      - name: run tests
        run: yarn test-cov
      - name: code climate
        uses: paambaati/codeclimate-action@v4.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
